/* jshint node: true */

module.exports = function(grunt) {

    var sources = [
        "src/js/viewport_controller.js",
        "src/js/shapes.js",
        "src/js/annotations_controller.js",
        "src/js/annotations_events_controller.js",
        "src/js/utils.js"
    ];

    grunt.initConfig({
        clean: {
            dist: [
                'build/js/ome_seadragon.js',
                'static/ome_seadragon/js/ome_seadragon.min.js'
            ]
        },
        concat: {
            options: {
                banner: "//! Built on <%= grunt.template.today('yyyy-mm-dd') %>\n" +
                    "//! GPL License.\n\n" +
                    "//!  DO NOT EDIT THIS FILE! - Edit under src/js/*.js\n\n",
                process: true,
                stripBanners: true,
            },
            dist: {
                src:  [ "<banner>" ].concat(sources),
                dest: "build/js/ome_seadragon.js"
            }
        },
        uglify: {
            options: {
                mangle: true
            },
            my_target: {
                files: {
                   "static/ome_seadragon/js/ome_seadragon.min.js" : ["build/js/ome_seadragon.js"],
                   "static/ome_seadragon/js/openseadragon-scalebar.min.js":["src/js/openseadragon-scalebar.js"]
                }
            }
        }
    });

    // Load tasks
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-contrib-uglify');

    // Register tasks
    grunt.registerTask('default', [
        'clean', 'concat', 'uglify'
    ]);

};