/*
 * Copyright (c) 2019, CRS4
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

/* jshint node: true */

module.exports = function(grunt) {

    var sources = [
        "src/js/viewport_controller.js",
        "src/js/shapes.js",
        "src/js/annotations_controller.js",
        "src/js/annotation_tools_manager.js",
        "src/js/image_marking_tool.js",
        "src/js/polygons_drawing_tool.js",
        "src/js/measuring_tool.js",
        "src/js/freehand_drawing_tool.js",
        "src/js/area_measuring_tool.js",
        "src/js/utils.js"
    ];

    grunt.initConfig({
        clean: {
            dist: [
                'build/js/ome_seadragon.js',
                'static/ome_seadragon/js/ome_seadragon.min.js'
            ]
        },
        concat: {
            options: {
                banner: "//! Built on <%= grunt.template.today('yyyy-mm-dd') %>\n" +
                    "//! GPL License.\n\n" +
                    "//!  DO NOT EDIT THIS FILE! - Edit under src/js/*.js\n\n",
                process: true,
                stripBanners: true,
            },
            dist: {
                src:  [ "<banner>" ].concat(sources),
                dest: "build/js/ome_seadragon.js"
            }
        },
        uglify: {
            options: {
                mangle: true
            },
            my_target: {
                files: {
                   "static/ome_seadragon/js/ome_seadragon.min.js" : ["build/js/ome_seadragon.js"],
                   "static/ome_seadragon/js/openseadragon-scalebar.min.js":["src/js/openseadragon-scalebar.js"]
                }
            }
        }
    });

    // Load tasks
    grunt.loadNpmTasks('grunt-contrib-clean');
    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-contrib-uglify');

    // Register tasks
    grunt.registerTask('default', [
        'clean', 'concat', 'uglify'
    ]);

};